services:
  frontend:
    build:
      context: ./whatsapp-clone
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
  backend:
    build:
      context: ./whatsapp-backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"